service: sms-sender

provider:
  name: google
  runtime: nodejs
  project: XXXXXX
  credentials: gcp-keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - gcp-keyfile.json

functions:
  sms:
    handler: sms
    events:
      - http: path
